### ISSUE TITLE
Can you help us to install it on unbuntu20.04?

### ISSUE THREAD

**Issue by ByteFlyCoding** [JackMoriarty/HillstoneVPN#1]
Can you help us to install it on unbuntu20.04? The vpn of my company is Hillstone Secure Connect. But I want use it on unbuntu20.04. It's sad that the offcial of Hillston Network did not support that the linux client install on ubuntu20.04. 
So, I want remove the Linux distritution judgment. Can you help me?

**Comment by JackMoriarty** [comment]
The offcial package only judges the linux distritution when you are installing, so you can install the offcial package on a supported platform such as Ubuntu Kylin16.04, the install program will put the executable file at the position where you  specify. copy the file to you machine. This should be worked.
 This repo also provides the executable file, you can download from release page directly.
